services:
  - type: web
    name: zakaria-outfit
    runtime: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libjpeg-dev zlib1g-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MAIN_KEY
        value: CTX-TEAM